# NATS konfiguracija za IoTS Projekat 3

port: 4222          # klijentski TCP port (Analytics mikroservis)
http_port: 8222     # monitoring / healthz

# WebSocket listener - bez njega se MqttNats aplikacija iz pregledača
# ne može pretplatiti na NATS subject
websocket {
  port: 9222
  no_tls: true
}

max_payload: 1MB
